name: Dispatch OpenAPI File Change event
on:
  push:
    branches: 
      - main
    paths:
      - "openapi/*.yaml"

jobs:
  dispatch:
    #env:
    #  APP_SERVICES_CI_TOKEN: ${{ secrets.APP_SERVICES_CI_TOKEN }}
    strategy:
      matrix:
        repo:
          - "jackdelahunt/app-services-sdk-core"
    runs-on: ubuntu-latest
    if: github.repository == 'jackdelahunt/i-hate-github-actions'
    steps:
      - uses: actions/checkout@v3
        
      - name: OpenAPI changed 
        uses: peter-evans/repository-dispatch@v2.1.0
        with:
          #token: ${{ env.APP_SERVICES_CI_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: openapi-spec-change
          client-payload: '{ "id": "smartevents-mgmt/v2", "download_url":"https://raw.githubusercontent.com/jackdelahunt/i-hate-github-actions/main/openapi/smartevents_mgmt_v2.yaml"}'
